### ISSUE TITLE
auroc.tsv in 7-transform.ipynb

### ISSUE THREAD

**Issue by maggielee1111** [dhimmel/learn#12]
Hi Daniel!

I'm trying to execute the notebook [7-transform.ipynb](https://github.com/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/all-features/7-transform.ipynb). In cell 2, there's a reference to the file `data/auroc.tsv` in the line `summary_df = readr::read_tsv('data/auroc.tsv')` but I couldn't locate this file in the repository. 

However, I did find a file named `auroc.tsv` located at [`data/feature-performance/auroc.tsv`](https://github.com/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/all-features/data/feature-performance/auroc.tsv). Its content seems different from what is expected in [7-transform.ipynb](https://github.com/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/all-features/7-transform.ipynb). 

Could you please guide me on how to obtain the correct `auroc.tsv` file as referenced in [7-transform.ipynb](https://github.com/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/all-features/7-transform.ipynb) notebook? I appreciate any assistance you can provide!

**Comment by dhimmel** [comment]
Hmm, I think `data/auroc.tsv` should be changed to [`data/feature-performance/primary-aurocs.tsv`](https://github.com/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/all-features/data/feature-performance/primary-aurocs.tsv), which appears to match the schema of `7-transform.ipynb` cell output 3.

Does that work?

Happy to accept a pull request with this file path change or other solution! Thanks for your interest.

**Comment by maggielee1111** [comment]
Yes! It works fine and the data frame seems correct. 
However the `funs_` function in cell 11 `none = function(x) {return(1)}`  of [7-transform.ipynb](https://github.com/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/all-features/7-transform.ipynb) was deprecated.  Just created a pull request for changing `aurocs.tsv` to `primary-aurocs.tsv`.

**Comment by dhimmel** [comment]
Thanks for the PR. Feel free to also update `dplyr::funs_` (in a new PR since I already merged https://github.com/dhimmel/learn/pull/13).
