### ISSUE TITLE
Can't find the Symptomatic validation dataset

### ISSUE THREAD

**Issue by lingling93** [dhimmel/learn#7]
Hi Daniel : 
I want evaluate my model exactly as you did with four validation datasets. Three of them(Disease Modifying, Clinical Trial, Drugcentral) are easy to get from the validation-datasets in your repository. I have not found the Symptomatic dataset yet. Can you help me with that ?
Thank you!
Lingling

**Comment by dhimmel** [comment]
Hi @lingling93, it looks like we compute the relevant performance visualizations and measures in the [`prediction/6-vizr.ipynb`](https://github.com/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/prediction/6-vizr.ipynb) R notebook. This notebook reads [`probabilities.tsv`](https://github.com/dhimmel/learn/blob/master/prediction/predictions/probabilities.tsv), which contains a `category` column. The positives for symptomatic indications are any pairs here with `SYM` for the category column. I believe the negatives are anything where category is blank (i.e. excluding the disease modifying `DM` indications).

The symptomatic and disease modifying indications come from [PharmacotherapyDB 1.0](https://doi.org/10.6084/m9.figshare.3103054.v1). More info on PharmacotherapyDB is available [here](https://doi.org/10.15363/thinklab.d182).

**Comment by dhimmel** [comment]
See https://github.com/dhimmel/learn/issues/9#issuecomment-594785230 for more information on computing the "Symptomatic" indication set of positives and negatives.
